export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Terminal palette — mapped to CSS variables for theme switching
        panel: "var(--c-panel)",
        "panel-hover": "var(--c-panel-hover)",
        "panel-active": "var(--c-panel-hover)",
        "panel-text": "var(--c-ink)",
        "panel-muted": "var(--c-ink-lighter)",
        "panel-dim": "var(--c-ink-faint)",
        surface: "var(--c-surface)",
        "surface-alt": "var(--c-surface-alt)",
        "surface-hover": "var(--c-panel-hover)",
        ink: "var(--c-ink)",
        "ink-light": "var(--c-ink-light)",
        "ink-lighter": "var(--c-ink-lighter)",
        "ink-faint": "var(--c-ink-faint)",
        "ink-ghost": "var(--c-ink-ghost)",
        accent: "var(--c-term-green)",
        "accent-text": "var(--c-accent-text)",
        "term-green": "var(--c-term-green)",
        "term-green-dim": "var(--c-term-green-dim)",
        "term-amber": "var(--c-term-amber)",
        "term-blue": "var(--c-term-blue)",
        "term-pink": "var(--c-term-pink)",
        "term-white": "var(--c-term-white)",
        danger: "var(--c-danger)",
        info: "var(--c-term-blue)",
        success: "var(--c-term-green)",
        warning: "var(--c-term-amber)",
        draft: "var(--c-term-amber)",
      },
      fontFamily: {
        sans: ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "4px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
