export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Vercel Dark palette
        bg: "var(--c-bg)",
        raised: "var(--c-raised)",
        "raised-hover": "var(--c-raised-hover)",
        "border-dim": "var(--c-border-dim)",
        "border-mid": "var(--c-border-mid)",
        ink: "var(--c-ink)",
        muted: "var(--c-muted)",
        faint: "var(--c-faint)",
        ghost: "var(--c-ghost)",
        // category dot colors
        "cat-blue": "var(--c-cat-blue)",
        "cat-purple": "var(--c-cat-purple)",
        "cat-amber": "var(--c-cat-amber)",
        "cat-pink": "var(--c-cat-pink)",
        "cat-green": "var(--c-cat-green)",
        danger: "var(--c-danger)",

        // Legacy aliases → vercel palette (so pre-port pages still render)
        panel: "var(--c-bg)",
        "panel-hover": "var(--c-raised)",
        "panel-active": "var(--c-raised)",
        "panel-text": "var(--c-ink)",
        "panel-muted": "var(--c-muted)",
        "panel-dim": "var(--c-faint)",
        surface: "var(--c-raised)",
        "surface-alt": "var(--c-raised)",
        "surface-hover": "var(--c-raised-hover)",
        "ink-light": "var(--c-ink)",
        "ink-lighter": "var(--c-muted)",
        "ink-faint": "var(--c-faint)",
        "ink-ghost": "var(--c-border-dim)",
        accent: "var(--c-ink)",
        "accent-text": "var(--c-bg)",
        "term-green": "var(--c-cat-green)",
        "term-green-dim": "var(--c-cat-green)",
        "term-amber": "var(--c-cat-amber)",
        "term-blue": "var(--c-cat-blue)",
        "term-pink": "var(--c-cat-pink)",
        "term-white": "var(--c-ink)",
        info: "var(--c-cat-blue)",
        success: "var(--c-cat-green)",
        warning: "var(--c-cat-amber)",
        draft: "var(--c-cat-amber)",
      },
      fontFamily: {
        sans: ["Geist", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "system-ui", "sans-serif"],
        mono: ['"Geist Mono"', "ui-monospace", '"SF Mono"', "Menlo", "monospace"],
      },
      borderRadius: {
        DEFAULT: "6px",
        md: "6px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        full: "9999px",
      },
      letterSpacing: {
        "tightest-plus": "-0.04em",
        "tighter-plus": "-0.03em",
      },
    },
  },
  plugins: [],
};
